### ISSUE TITLE
XDP DDoS for game servers

### ISSUE THREAD

**Issue by vincentmli** [mas-bandwidth/xdp#1]
Hi @gafferongames 

 [Bill Mulligan](https://github.com/xmulligan) linkedin reference to your article leads me here. very interesting read. I happen to be working on IPFire firewall to enable XDP DDoS for game servers, looks we share the same interest :) see my video [Enable IPFire ePBF XDP DDoS from WebUI](https://youtu.be/1pdNgoP-Kho?si=apF-0U8C9WtunItB)

**Comment by gafferongames** [comment]
Nice!
